name: Production Build and Deploy
run-name: Production CI/CD ${{ github.event_name }} by @${{ github.actor }}

on:
  workflow_dispatch:

jobs:
  build-and-push-image:
    runs-on: ubuntu-22.04
    outputs:
      short_sha: ${{ steps.vars.outputs.short_sha }}

    steps:
    - name: Checkout repository
      id: github
      uses: actions/Checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '9.0.x'

    - name: Configure Azure Container Registry (ACR)
      uses: azure/docker-login@v2
      with:
        login-server: ${{ vars.PROD_ACR_SERVER }}
        username: ${{ secrets.PROD_ACR_USER }}
        password: ${{ secrets.PROD_ACR_PASSWORD }}

    - name: Get commit SHA
      id: vars
      run: |
        getSha=$(git rev-parse --short ${{ github.sha }})
        echo "::set-output name=short_sha::$getSha"

    - name: Build and push image to Azure Container Registry (ACR)
      working-directory: ./
      env:
        ACR_REGISTRY: ${{ vars.PROD_ACR_SERVER }}
        ACR_USER: ${{ secrets.PROD_ACR_USER }}
        IMAGE_TAG: ${{ steps.vars.outputs.short_sha }}
      run: |
        docker build -f Dockerfile -t $ACR_REGISTRY/$ACR_USER:$IMAGE_TAG .
        docker push $ACR_REGISTRY/$ACR_USER --all-tags

  deploy-image-to-container-service:
    runs-on: ubuntu-22.04
    needs: build-and-push-image

    steps:
      - name: Login to Azure
        uses: azure/login/@v1
        with:
          creds: ${{ secrets.PROD_AZ_CREDENTIALS }}

      - name: Deploy to Azure Container Apps (ACA)
        uses: azure/container-apps-deploy-action@v1
        env:
          IMAGE_TAG: ${{ needs.build-and-push-image.outputs.short_sha }}
          ACR_SERVER: ${{ vars.PROD_ACR_SERVER }}
          ACR_USER: ${{ secrets.PROD_ACR_USER }}
          DB_CONN: ${{ secrets.PROD_AZ_PGSQL_DB_CONN }}
        with:
          registryUrl: ${{ vars.PROD_ACR_SERVER }}
          imageToDeploy: $ACR_SERVER/$ACR_USER:$IMAGE_TAG
          targetPort: 8080
          ingress: external
          containerAppName: resolv-prod
          containerAppEnvironment: resolv-prod
          resourceGroup: resolv-prod-rg
          environmentVariables: Database__ResolvDb__ConnectionString=${{ secrets.PROD_AZ_PGSQL_DB_CONN }} ASPNETCORE_ENVIRONMENT=Production Logging__LogLevel__Default=Warning